# Generated by Django 5.2.8 on 2026-01-25 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0002_alter_attempt_options_alter_mailing_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_manage_mailings", "Может управлять рассылками"),
                    ("send_mailing", "Может отправлять рассылки"),
                ],
                "verbose_name": "Рассылка",
                "verbose_name_plural": "Рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [("can_manage_messages", "Может управлять сообщениями")],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.AlterModelOptions(
            name="recipient",
            options={
                "permissions": [
                    ("can_manage_recipients", "Может управлять получателями")
                ],
                "verbose_name": "Получатель",
                "verbose_name_plural": "Получатели",
            },
        ),
    ]
