# Generated by Django 5.2.8 on 2026-01-25 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="country",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Страна"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="Обязательное поле. Укажите корректный email.",
                max_length=254,
                unique=True,
                verbose_name="email address",
            ),
        ),
    ]
